[database]
DATABASE_URL = "postgresql://resumerelevance_user:m9AU1Io4ZVbS3WQnl95dNzXGzHbApATm@dpg-d37pdvvfte5s73bflj9g-a.oregon-postgres.render.com/resumerelevance"

[api]
GOOGLE_API_KEY = "AIzaSyDO8uuSRqnt6i8DDE5AfTeOLEniZNObV54"
